---
#have mixed feelings with the way i did this.
#Ideally i would only issue commands to filesystem and mount but i had
#issues with the previously configured raid setup.
#Going to make formatting and mounting optional
- name: check for file system
  shell:  " lsblk -f /dev/{{ item }}  | grep 'ext[2-4]' "
  ignore_errors: True
  register: formatted
  with_items:  hostvars[inventory_hostname]["ansible_devices"].keys()
  when: not  hostvars[inventory_hostname]["ansible_devices"][item]["partitions"]
  tags:
    - cdh

- shell: echo bleh {{ item.item }}
  with_items: "{{ formatted.results }}"
  when: " item.changed and not item.stdout"
  tags:
    - cdh

- filesystem: 
    force: yes 
    dev: /dev/{{ item.item }} 
    fstype: "{{ fstype }}"
  with_items: "{{ formatted.results }}"
  when: " item.changed and not item.stdout"
  tags:
    - cdh

- mount:
    name: /{{ hdfs_mount  }}/{{item.item}}
    src: /dev/{{ item.item }}
    fstype: "{{ fstype }}"
    state: mounted
    opts: "noatime"
  with_items:  "{{ formatted.results }}"
  when: " item.changed and item.stdout " 
  tags:
    - cdh
